import type { Metadata } from 'next';
import { Geist, Geist_Mono } from 'next/font/google';
import '@rt/styles/globals.css';
import { Toaster } from '@rt/components/ui/sonner';
import Header from '@rt/components/Header';
import { SidebarProvider } from '@rt/components/ui/sidebar';
import AppSidebar from '@rt/components/AppSidebar';
import { ThemeProvider } from '@rt/providers/ThemeProvider';
import NoteProvider from '@rt/providers/NoteProvider';

const geistSans = Geist({
  variable: '--font-geist-sans',
  subsets: ['latin'],
});

const geistMono = Geist_Mono({
  variable: '--font-geist-mono',
  subsets: ['latin'],
});

export const metadata: Metadata = {
  title: 'AI Note Taking App',
  description: 'Generated by OpenAI',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <ThemeProvider
          attribute="class"
          defaultTheme="dark"
          enableSystem
          disableTransitionOnChange
        >
          <NoteProvider>
            <SidebarProvider>
              <AppSidebar />
              <div className="flex min-h-screen w-full flex-col">
                <Header />
                <main className="flex flex-1 flex-col px-4 pt-10 xl:px-8">
                  {children}
                </main>
                <Toaster />
              </div>
            </SidebarProvider>
          </NoteProvider>
        </ThemeProvider>
      </body>
    </html>
  );
}
