import type { Metadata } from 'next';
import { Geist, Geist_Mono } from 'next/font/google';
import '@rt/styles/globals.css';
import { ThemeProvider } from '@rt/components/theme-provider';
import { Toaster } from '@rt/components/ui/sonner';
import Header from '@rt/components/Header';
import { SidebarProvider } from '@rt/components/ui/sidebar';
import { AppSidebar } from '@rt/components/AppSidebar';

const geistSans = Geist({
  variable: '--font-geist-sans',
  subsets: ['latin'],
});

const geistMono = Geist_Mono({
  variable: '--font-geist-mono',
  subsets: ['latin'],
});

export const metadata: Metadata = {
  title: 'AI Note Taking App',
  description: 'Generated by OpenAI',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <ThemeProvider
          attribute="class"
          defaultTheme="dark"
          enableSystem
          disableTransitionOnChange
        >
          <SidebarProvider>
            <div className="flex min-h-screen w-full flex-col">
              <Header />
              <AppSidebar />
              <main className="flec-col flex flex-1 px-4 pt-10 xl:px-8">
                {children}
              </main>
              <Toaster />
            </div>
          </SidebarProvider>
        </ThemeProvider>
      </body>
    </html>
  );
}
