import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import '@rt/styles/globals.css';
import { ThemeProvider } from "@rt/components/theme-provider";
import { ModeToggle } from "@rt/components/header";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "AI Note Taking App",
  description: "Generated by OpenAI",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <ThemeProvider
            attribute="class"
            defaultTheme='dark'
            enableSystem
            disableTransitionOnChange
          >

<ModeToggle/>
        {children}  </ThemeProvider>
      </body>
    </html>
  );
}
